/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/products": {
    get: {
      parameters: {
        query: {
          product_id?: parameters["rowFilter.products.product_id"];
          product_name?: parameters["rowFilter.products.product_name"];
          description?: parameters["rowFilter.products.description"];
          price?: parameters["rowFilter.products.price"];
          stock?: parameters["rowFilter.products.stock"];
          image_url?: parameters["rowFilter.products.image_url"];
          created_at?: parameters["rowFilter.products.created_at"];
          updated_at?: parameters["rowFilter.products.updated_at"];
          delete_flg?: parameters["rowFilter.products.delete_flg"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["products"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** products */
          products?: definitions["products"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          product_id?: parameters["rowFilter.products.product_id"];
          product_name?: parameters["rowFilter.products.product_name"];
          description?: parameters["rowFilter.products.description"];
          price?: parameters["rowFilter.products.price"];
          stock?: parameters["rowFilter.products.stock"];
          image_url?: parameters["rowFilter.products.image_url"];
          created_at?: parameters["rowFilter.products.created_at"];
          updated_at?: parameters["rowFilter.products.updated_at"];
          delete_flg?: parameters["rowFilter.products.delete_flg"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          product_id?: parameters["rowFilter.products.product_id"];
          product_name?: parameters["rowFilter.products.product_name"];
          description?: parameters["rowFilter.products.description"];
          price?: parameters["rowFilter.products.price"];
          stock?: parameters["rowFilter.products.stock"];
          image_url?: parameters["rowFilter.products.image_url"];
          created_at?: parameters["rowFilter.products.created_at"];
          updated_at?: parameters["rowFilter.products.updated_at"];
          delete_flg?: parameters["rowFilter.products.delete_flg"];
        };
        body: {
          /** products */
          products?: definitions["products"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  products: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    product_id: number;
    /** Format: character varying */
    product_name: string;
    /** Format: text */
    description?: string;
    /** Format: integer */
    price: number;
    /** Format: integer */
    stock: number;
    /**
     * Format: character varying
     * @default NULL
     */
    image_url?: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    created_at: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    updated_at: string;
    /** Format: boolean */
    delete_flg: boolean;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description products */
  "body.products": definitions["products"];
  /** Format: integer */
  "rowFilter.products.product_id": string;
  /** Format: character varying */
  "rowFilter.products.product_name": string;
  /** Format: text */
  "rowFilter.products.description": string;
  /** Format: integer */
  "rowFilter.products.price": string;
  /** Format: integer */
  "rowFilter.products.stock": string;
  /** Format: character varying */
  "rowFilter.products.image_url": string;
  /** Format: timestamp without time zone */
  "rowFilter.products.created_at": string;
  /** Format: timestamp without time zone */
  "rowFilter.products.updated_at": string;
  /** Format: boolean */
  "rowFilter.products.delete_flg": string;
}

export interface operations {}

export interface external {}
